version: '3.7'

services:
  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/basicBoard/src
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - my-database
    networks:
      - board-network
    env_file:
      - ./backend/.env.docker

  my-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 5500:80
    depends_on:
      - my-backend
    networks:
      - board-network

  my-database:
    image: mongo:5
    ports:
      - 27017:27017
    networks:
      - board-network

networks:
  board-network:
    driver: bridge
