version: '3.7'

services:
  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/basicBoard/src
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - my-database
    networks:
      - board-network
    env_file:
      - ./backend/.env.docker
    restart: always

  my-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - my-backend
    networks:
      - board-network
    restart: always

  my-database:
    image: mongo:5
    ports:
      - ${DATABASE_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - board-network
    restart: always

networks:
  board-network:
    driver: bridge
